apiVersion: v1
kind: Pod
metadata:
  name: netperf-client
spec:
  containers:
    - name: client
      command: ["sleep", "99999999"]
      image: tomopiro/netperf

---
apiVersion: v1
kind: Pod
metadata:
  name: netperf-server
  labels:
    app: netperf-server
spec:
  containers:
    - name: server
      image: tomopiro/netperf
      command: ["netserver", "-D", "-L", "0.0.0.0"]

---
apiVersion: v1
kind: Service
metadata:
  name: netperf-server
spec:
  selector:
    app: netperf-server
  ports:
    - name: tcp
      protocol: TCP
      port: 12865
      targetPort: 12865
    - name: udp
      protocol: UDP
      port: 12865
      targetPort: 12865
    - name: tcp-control
      protocol: TCP
      port: 12000
      targetPort: 12000
    - name: udp-control
      protocol: UDP
      port: 12000
      targetPort: 12000
