apiVersion: v1
kind: Pod
metadata:
  name: iperf2-client
spec:
  containers:
    - name: client
      command: ["sleep", "99999999"]
      image: tomopiro/netperf:latest

---
apiVersion: v1
kind: Pod
metadata:
  name: iperf2-server
  labels:
    app: iperf2-server
spec:
  containers:
    - name: server
      image: tomopiro/netperf:latest
      command: ["iperf", "-s"]

---
apiVersion: v1
kind: Service
metadata:
  name: iperf2-server
spec:
  selector:
    app: iperf2-server
  ports:
    - name: tcp
      protocol: TCP
      port: 5001
      targetPort: 5001
    - name: udp
      protocol: UDP
      port: 5001
      targetPort: 5001
