apiVersion: v1
kind: Pod
metadata:
  name: iperf3-client
spec:
  containers:
    - name: client
      command: ["sleep", "99999999"]
      image: tomopiro/netperf

---
apiVersion: v1
kind: Pod
metadata:
  name: iperf3-server
  labels:
    app: iperf3-server
spec:
  containers:
    - name: server
      image: tomopiro/netperf
      command: ["iperf3", "-s"]

---
apiVersion: v1
kind: Service
metadata:
  name: iperf3-server
spec:
  selector:
    app: iperf3-server
  ports:
    - name: tcp
      protocol: TCP
      port: 5201
      targetPort: 5201
    - name: udp
      protocol: UDP
      port: 5201
      targetPort: 5201
